export const apiKeys = {
  users: () => ["users"],
  cards: () => ["cards"],
  recentTransactions: () => ["recentTransactions"],
  expenses: () => ["expenses"],
  weeklyActivity: () => ["weeklyActivity"],
  friends: () => ["friends"],
  balanceHistory: () => ["balanceHistory"],
  userById: (id: string) => [...apiKeys.users(), id],
  cardsById: (id: string) => [...apiKeys.cards(), id],
  recentTransactionsById: (id: string) => [...apiKeys.recentTransactions(), id],
  expensesById: (id: string) => [...apiKeys.expenses(), id],
  weeklyActivityById: (id: string) => [...apiKeys.weeklyActivity(), id],
  friendsById: (id: string) => [...apiKeys.friends(), id],
  balanceHistoryById: (id: string) => [...apiKeys.balanceHistory(), id],
};
